CREATE TABLE BANK_CUSTOMERS1 (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    DOB DATE,
    Balance NUMBER
);

CREATE TABLE BANK_LOANS1 (
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    LoanAmount NUMBER,
    InterestRate NUMBER,
    StartDate DATE,
    EndDate DATE
);

INSERT INTO BANK_CUSTOMERS1 VALUES (1,'Balaji',TO_DATE('1960-05-15','YYYY-MM-DD'),15000);
INSERT INTO BANK_CUSTOMERS1 VALUES (2,'Arun',TO_DATE('1998-07-10','YYYY-MM-DD'),8000);
INSERT INTO BANK_CUSTOMERS1 VALUES (3,'Danny',TO_DATE('1955-02-20','YYYY-MM-DD'),25000);

INSERT INTO BANK_LOANS1 VALUES (101,1,500000,9,SYSDATE,SYSDATE+20);
INSERT INTO BANK_LOANS1 VALUES (102,2,300000,10,SYSDATE,SYSDATE+50);
INSERT INTO BANK_LOANS1 VALUES (103,3,700000,8,SYSDATE,SYSDATE+15);

COMMIT;

BEGIN
    FOR rec IN (
        SELECT c.CustomerID, l.LoanID
        FROM BANK_CUSTOMERS1 c
        JOIN BANK_LOANS1 l ON c.CustomerID = l.CustomerID
        WHERE TRUNC(MONTHS_BETWEEN(SYSDATE, c.DOB)/12) > 60
    )
    LOOP
        UPDATE BANK_LOANS1
        SET InterestRate = InterestRate - 1
        WHERE LoanID = rec.LoanID;
    END LOOP;
END;
/

SELECT * FROM BANK_LOANS1;