CREATE TABLE BANK_CUSTOMERS2 (
    CustomerID NUMBER PRIMARY KEY,
    Name VARCHAR2(100),
    DOB DATE,
    Balance NUMBER
);

INSERT INTO BANK_CUSTOMERS2 VALUES (1,'Balaji',TO_DATE('1960-05-15','YYYY-MM-DD'),15000);
INSERT INTO BANK_CUSTOMERS2 VALUES (2,'Arun',TO_DATE('1998-07-10','YYYY-MM-DD'),8000);
INSERT INTO BANK_CUSTOMERS2 VALUES (3,'Danny',TO_DATE('1955-02-20','YYYY-MM-DD'),25000);

COMMIT;

BEGIN
    FOR rec IN (
        SELECT CustomerID, Name, Balance
        FROM BANK_CUSTOMERS2
        WHERE Balance > 10000
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE('VIP Customer: ' || rec.Name);
    END LOOP;
END;
/