CREATE TABLE BANK_LOANS3 (
    LoanID NUMBER PRIMARY KEY,
    CustomerID NUMBER,
    LoanAmount NUMBER,
    InterestRate NUMBER,
    StartDate DATE,
    EndDate DATE
);

INSERT INTO BANK_LOANS3 VALUES (101,1,500000,9,SYSDATE,SYSDATE+20);
INSERT INTO BANK_LOANS3 VALUES (102,2,300000,10,SYSDATE,SYSDATE+50);
INSERT INTO BANK_LOANS3 VALUES (103,3,700000,8,SYSDATE,SYSDATE+15);

COMMIT;

BEGIN
    FOR rec IN (
        SELECT LoanID, CustomerID, EndDate
        FROM BANK_LOANS3
        WHERE EndDate BETWEEN SYSDATE AND SYSDATE + 30
    )
    LOOP
        DBMS_OUTPUT.PUT_LINE('Reminder for Loan ID: ' || rec.LoanID);
    END LOOP;
END;
/